# http://docs.travis-ci.com/user/build-configuration/
language: cpp

sudo: false

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libunittest++-dev
            - python
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      after_success:
        - make coverage
        - pip install --user --upgrade pip
        - pip install --user git+http://github.com/eddyxu/cpp-coveralls.git
        - coveralls --gcov /usr/bin/gcov-8 -e /usr/
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-6.0
            - libunittest++-dev
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
    - eval "${MATRIX_EVAL}"
    - export UNITTEST_CPP_INCLUDE=/usr/include/unittest++

script:
  - make tests

notifications:
  irc:
    channels:
      #  - "irc.freenode.org#imaginaerraum"
    skip_join: true
    use_notice: true
    template:
      #- "[%{commit}: %{author}] %{message}"
      #- "%{build_url}"
      - "[%{repository_slug}#%{branch} @%{commit}] (%{author}): %{message}"
      - "Diff: %{compare_url}"
      - "Build: %{build_url}"
