# http://docs.travis-ci.com/user/build-configuration/
language: cpp

sudo: false

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libunittest++-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty
          packages:
            - clang-5.0
            - libunittest++-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - make tests

notifications:
  irc:
    channels:
      - "irc.freenode.org#imaginaerraum"
    skip_join: true
    use_notice: true
    template:
      #- "[%{commit}: %{author}] %{message}"
      #- "%{build_url}"
      - "[%{repository_slug}#%{branch} @%{commit}] (%{author}): %{message}"
      - "Diff: %{compare_url}"
      - "Build: %{build_url}"
