# http://docs.travis-ci.com/user/build-configuration/
language: cpp

sudo: false

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libunittest++-dev
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      after_success:
        - make coverage
        - coveralls 
    - os: linux
      addons:
        apt:
          packages:
            - libunittest++-dev
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
    - eval "${MATRIX_EVAL}"
    - pip install --user cpp-coveralls
    - export UNITTEST_CPP_INCLUDE=/usr/include/unittest++

script:
  - make tests

notifications:
  irc:
    channels:
      #  - "irc.freenode.org#imaginaerraum"
    skip_join: true
    use_notice: true
    template:
      #- "[%{commit}: %{author}] %{message}"
      #- "%{build_url}"
      - "[%{repository_slug}#%{branch} @%{commit}] (%{author}): %{message}"
      - "Diff: %{compare_url}"
      - "Build: %{build_url}"
